const REQUEST_QUESTION_CATEGORIES = "REQUEST_QUESTION_CATEGORIES";
const SUCCESS_QUESTION_CATEGORIES = "SUCCESS_QUESTION_CATEGORIES";
const ERROR_QUESTION_CATEGORIES = "ERROR_QUESTION_CATEGORIES";

const SELECT_QUESTION_CATEGORY = "SELECT_QUESTION_CATEGORY";

const selectQuestionCategory = categoryID => ({
  type: SELECT_QUESTION_CATEGORY,
  categoryID
});

export {
  REQUEST_QUESTION_CATEGORIES,
  SUCCESS_QUESTION_CATEGORIES,
  ERROR_QUESTION_CATEGORIES,
  SELECT_QUESTION_CATEGORY,
  selectQuestionCategory
};
