const REQUEST_SURVEY_AGGREGATE_RESULTS = "REQUEST_SURVEY_AGGREGATE_RESULTS";
const SUCCESS_SURVEY_AGGREGATE_RESULTS = "SUCCESS_SURVEY_AGGREGATE_RESULTS";
const ERROR_SURVEY_AGGREGATE_RESULTS = "ERROR_SURVEY_AGGREGATE_RESULTS";

export {
  REQUEST_SURVEY_AGGREGATE_RESULTS,
  SUCCESS_SURVEY_AGGREGATE_RESULTS,
  ERROR_SURVEY_AGGREGATE_RESULTS
};
